# Generated by Django 5.0.2 on 2024-02-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookTicket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookaticket',
            options={'verbose_name_plural': 'Booked Tickets'},
        ),
    ]
